In [1]:
import tensorflow as tf
tf.enable_eager_execution()
import keras.backend as K
import keras
import numpy as np

Using TensorFlow backend.


# Test  binary classification using

    Use keras.losses.binary_crossentropy
    predictions should come from sigmoid activatiion

In [2]:
'''fake data'''
a = tf.constant(np.random.randint(0., 2., [3,1]), dtype=tf.float32)
b = tf.constant(np.random.random([3,1]), dtype=tf.float32)
a, b

(<tf.Tensor: id=0, shape=(3, 1), dtype=float32, numpy=
 array([[0.],
        [1.],
        [0.]], dtype=float32)>,
 <tf.Tensor: id=1, shape=(3, 1), dtype=float32, numpy=
 array([[0.327229  ],
        [0.75215155],
        [0.16013725]], dtype=float32)>)

In [3]:
'''binary_crossentropy'''
loss = keras.losses.binary_crossentropy(a, b)
loss.numpy(), K.mean(loss).numpy()

(array([0.3963503 , 0.28481746, 0.1745168 ], dtype=float32), 0.28522816)

# Test multi-class classification

    Use keras.losses.categorical_crossentropy
    predictions should come from softmax activatiion

In [4]:
'''fake data'''
a = tf.constant(np.random.randint(0, 2, [3,2]), dtype=tf.float32)
b = tf.constant(np.random.random([3,2]), dtype=tf.float32)
a, b

(<tf.Tensor: id=29, shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32)>,
 <tf.Tensor: id=30, shape=(3, 2), dtype=float32, numpy=
 array([[0.9231248 , 0.8521743 ],
        [0.75054324, 0.11818382],
        [0.0120418 , 0.66685826]], dtype=float32)>)

In [5]:
'''categorical_crossentropy'''
loss = keras.losses.categorical_crossentropy(a, b)
loss.numpy(), K.mean(loss).numpy()

(array([1.387893 , 1.9947878, 0.0178964], dtype=float32), 1.1335257)

# Test scalar regression

    Use L1, L2 loss
    predictions should come from sigmoid activatiion

In [6]:
'''fake data'''
a = tf.constant(np.random.random([3,1]), dtype=tf.float32)
b = tf.constant(np.random.random([3,1]), dtype=tf.float32)
a, b

(<tf.Tensor: id=50, shape=(3, 1), dtype=float32, numpy=
 array([[0.06820133],
        [0.03455216],
        [0.19332492]], dtype=float32)>,
 <tf.Tensor: id=51, shape=(3, 1), dtype=float32, numpy=
 array([[0.4572509],
        [0.2334912],
        [0.2614802]], dtype=float32)>)

In [7]:
'''L1 loss'''
loss = keras.losses.mean_absolute_error(a, b)
loss.numpy(), K.mean(loss).numpy()

(array([0.38904956, 0.19893904, 0.06815529], dtype=float32), 0.21871464)

In [8]:
'''L2 loss'''
loss = keras.losses.mean_squared_error(a, b)
loss.numpy(), K.mean(loss).numpy()

(array([0.15135956, 0.03957674, 0.00464514], dtype=float32), 0.06519381)

# Test vector regression

    Use L1, L2, smooth_L1 loss
    predictions should come from sigmoid activatiion

In [9]:
'''fake data'''
a = tf.constant(np.random.random([2,4]), dtype=tf.float32)
b = tf.constant(np.random.random([2,4]), dtype=tf.float32)
a, b

(<tf.Tensor: id=70, shape=(2, 4), dtype=float32, numpy=
 array([[0.60530937, 0.3320059 , 0.30998054, 0.89274734],
        [0.43584523, 0.75255203, 0.46186432, 0.6340625 ]], dtype=float32)>,
 <tf.Tensor: id=71, shape=(2, 4), dtype=float32, numpy=
 array([[0.37371716, 0.8641324 , 0.9754876 , 0.36951992],
        [0.10038423, 0.3271374 , 0.04779791, 0.90426576]], dtype=float32)>)

In [10]:
'''L1 loss'''
loss = keras.losses.mean_absolute_error(a, b)
loss.numpy(), K.mean(loss).numpy()

(array([0.4881133, 0.3612863], dtype=float32), 0.4246998)

In [11]:
'''L2 loss'''
loss = keras.losses.mean_squared_error(a, b)
loss.numpy(), K.mean(loss).numpy()

(array([0.26336506, 0.13449311], dtype=float32), 0.19892909)

In [12]:
'''smooth_L1 lossm (actually this is Huber loss)'''
def smooth_l1_loss(y_true, y_pred):
    '''
    inputs:
        y_true: [n, 1]
        y_pred: [n, 1]
    '''    
    diff = K.abs(y_true - y_pred)
    less_than_one = K.cast(K.less(diff, 1.0), "float32")
    loss = (less_than_one * 0.5 * diff**2) + (1 - less_than_one) * (diff - 0.5)
    return K.sum(loss, axis=1)


In [13]:
loss = smooth_l1_loss(a, b)
loss.numpy(), K.mean(loss).numpy()

(array([0.5267301 , 0.26898623], dtype=float32), 0.39785817)